package main
SCREEN_WIDTH :: 1280

SCREEN_HEIGHT :: 720

WORLD_SIZE :: Vec2f{SCREEN_WIDTH, SCREEN_HEIGHT}
PARTICLES_SQUARE_SIDE :: 40 
NUM_PARTICLES :: PARTICLES_SQUARE_SIDE * PARTICLES_SQUARE_SIDE

PARTICLE_RADIUS :: 5
PARTICLE_PADDING :: 15

NUM_CELLS :: 100000
CELL_SIZE :: 25
COLLISION_RADIUS_SQUARED :: CELL_SIZE * CELL_SIZE

MAX_VELOCITY_MODULUS :: 100
GRAVITY :: Vec2f{0, 10}

REST_DENSITY :: 40

FPS:: 60

PARTICLE_CENTER_OFFSET :: Vec2f{PARTICLE_RADIUS / 2.0, PARTICLE_RADIUS / 2.0}
